### ISSUE TITLE
Pyqt5 broken

### ISSUE THREAD

**Issue by uhve** [nooballiance/password-manager-gone-wrong#3]
broken code, check if it runs separately!

**Comment by akhileshdhaundiyal** [comment]
![image](https://user-images.githubusercontent.com/20400763/37565464-e8550146-2acf-11e8-9164-a4e61e6efa8a.png)
it works flawlessly, check if you have required packages

**Comment by uhve** [comment]
![image](https://user-images.githubusercontent.com/9166890/37565587-d5db8e5c-2ad1-11e8-971d-997dd9f910de.png)

**Comment by akhileshdhaundiyal** [comment]
![image](https://user-images.githubusercontent.com/20400763/37565731-662f7eda-2ad4-11e8-98cf-94e01bfa72d5.png)
Breath-Dark theme
